version: "3.4"


# NOTE: This _has _to start with `x-`
x-logging: &default-logging
  options:
    max-size: "20k"
    max-file: "10"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn myproject.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    stdin_open: true
    tty: true
    logging: *default-logging

  db:
    image: postgres:13-alpine
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    logging: *default-logging

volumes:
  db_data:
